server:
  port: 8080
value: 13 
person:
  name: "ds"
  age: 14 
spring: 
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/traffic-tools
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
         hbm2dd1:
           auto: update
         dialect:  org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true   
      